/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sala18a
 */
public class CadastroAluno extends javax.swing.JFrame {

    /**
     * Creates new form telaAluno
     */
    public CadastroAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jTextCod_alunos3 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextNome_alunos2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextNome_alunos1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextNome_alunos = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Do Aluno");
        getContentPane().setLayout(null);

        jButton6.setBackground(new java.awt.Color(0, 102, 51));
        jButton6.setText("Salvar");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(180, 430, 90, 50);

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setText("Voltar");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 430, 90, 50);

        jLabel11.setText("Senha");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 290, 60, 14);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(80, 290, 80, 20);

        jLabel12.setText("Login");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(40, 260, 63, 14);

        jTextCod_alunos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCod_alunos3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCod_alunos3);
        jTextCod_alunos3.setBounds(80, 260, 75, 20);

        jLabel13.setText("Email");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(40, 230, 60, 14);

        jTextNome_alunos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_alunos2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome_alunos2);
        jTextNome_alunos2.setBounds(80, 230, 170, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Noturno", "Integral" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(80, 200, 90, 20);

        jLabel14.setText("Turno");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 200, 63, 14);

        jLabel15.setText("Matricula");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 170, 60, 14);

        jTextNome_alunos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_alunos1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome_alunos1);
        jTextNome_alunos1.setBounds(90, 170, 50, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(90, 140, 40, 20);

        jLabel16.setText("Série");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 140, 63, 14);

        jLabel17.setText("Nome");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(40, 110, 60, 14);

        jTextNome_alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_alunosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome_alunos);
        jTextNome_alunos.setBounds(80, 110, 100, 20);

        jPanel10.setBackground(new java.awt.Color(0, 153, 0));
        jPanel10.setToolTipText("Teste");
        jPanel10.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CADASTRO ALUNO");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.setFocusable(false);
        jPanel10.add(jLabel10);
        jLabel10.setBounds(80, -20, 510, 150);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(0, 0, 610, 100);

        setSize(new java.awt.Dimension(621, 534));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextCod_alunos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCod_alunos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCod_alunos3ActionPerformed

    private void jTextNome_alunos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_alunos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_alunos2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextNome_alunos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_alunos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_alunos1ActionPerformed

    private void jTextNome_alunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_alunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_alunosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextCod_alunos3;
    private javax.swing.JTextField jTextNome_alunos;
    private javax.swing.JTextField jTextNome_alunos1;
    private javax.swing.JTextField jTextNome_alunos2;
    // End of variables declaration//GEN-END:variables
}
