/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sala18a
 */
public class CriarExercicios extends javax.swing.JFrame {

    /**
     * Creates new form CriarExercicios
     */
    public CriarExercicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextNome_Exercicios = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextQuestao_Exercicios3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jTextNome_Exercicios1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextNome_Exercicios3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jTextNome_Exercicios4 = new javax.swing.JTextField();
        bVoltarCriarExercicios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel18.setBackground(new java.awt.Color(0, 153, 0));
        jPanel18.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("CRIAR EXERCÍCIOS");
        jPanel18.add(jLabel30);
        jLabel30.setBounds(50, 10, 530, 100);

        getContentPane().add(jPanel18);
        jPanel18.setBounds(0, 0, 610, 120);

        jLabel31.setText("Professor");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(20, 160, 70, 14);

        jTextNome_Exercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_ExerciciosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome_Exercicios);
        jTextNome_Exercicios.setBounds(100, 430, 30, 20);

        jLabel32.setText("Questão ");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(20, 220, 60, 20);

        jTextQuestao_Exercicios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuestao_Exercicios3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextQuestao_Exercicios3);
        jTextQuestao_Exercicios3.setBounds(20, 240, 450, 100);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(30, 350, 21, 21);

        jLabel33.setText("Título");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(20, 190, 70, 14);

        jTextNome_Exercicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome_Exercicios1);
        jTextNome_Exercicios1.setBounds(80, 160, 110, 20);

        jButton5.setText("ADICIONAR QUESTÃO");
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 460, 160, 30);

        jLabel34.setText("Resposta");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(30, 430, 60, 14);

        jTextNome_Exercicios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome_Exercicios3);
        jTextNome_Exercicios3.setBounds(80, 190, 130, 20);

        jButton7.setText("ADICIONAR OPÇÃO");
        getContentPane().add(jButton7);
        jButton7.setBounds(30, 390, 140, 30);

        jTextNome_Exercicios4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome_Exercicios4);
        jTextNome_Exercicios4.setBounds(70, 350, 430, 30);

        bVoltarCriarExercicios.setBackground(new java.awt.Color(0, 102, 51));
        bVoltarCriarExercicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarCriarExercicios.setForeground(new java.awt.Color(255, 255, 255));
        bVoltarCriarExercicios.setText("Voltar");
        bVoltarCriarExercicios.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bVoltarCriarExercicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarCriarExercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarCriarExerciciosActionPerformed(evt);
            }
        });
        getContentPane().add(bVoltarCriarExercicios);
        bVoltarCriarExercicios.setBounds(480, 540, 100, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNome_ExerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_ExerciciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_ExerciciosActionPerformed

    private void jTextQuestao_Exercicios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuestao_Exercicios3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestao_Exercicios3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextNome_Exercicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios1ActionPerformed

    private void jTextNome_Exercicios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios3ActionPerformed

    private void jTextNome_Exercicios4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios4ActionPerformed

    private void bVoltarCriarExerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarCriarExerciciosActionPerformed

    }//GEN-LAST:event_bVoltarCriarExerciciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarExercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bVoltarCriarExercicios;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextNome_Exercicios;
    private javax.swing.JTextField jTextNome_Exercicios1;
    private javax.swing.JTextField jTextNome_Exercicios3;
    private javax.swing.JTextField jTextNome_Exercicios4;
    private javax.swing.JTextField jTextQuestao_Exercicios3;
    // End of variables declaration//GEN-END:variables
}
