/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author sala18a
 */
public class CriarExercicios extends javax.swing.JFrame {

    /**
     * Creates new form CriarExercicios
     */
    public CriarExercicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNome_Exercicios = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextQuestao_Exercicios1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jTextNome_Exercicios1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextNome_Exercicios3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextNome_Exercicios4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Criar Exercícios");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 30, 410, 75);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 970, 140);

        jLabel2.setText("Professor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 160, 70, 14);

        jTextNome_Exercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_ExerciciosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome_Exercicios);
        jTextNome_Exercicios.setBounds(80, 560, 30, 20);

        jLabel4.setText("Questão ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 250, 60, 20);

        jTextQuestao_Exercicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuestao_Exercicios1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextQuestao_Exercicios1);
        jTextQuestao_Exercicios1.setBounds(20, 280, 450, 160);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(70, 460, 21, 21);

        jLabel3.setText("Título");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 210, 70, 14);

        jTextNome_Exercicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome_Exercicios1);
        jTextNome_Exercicios1.setBounds(80, 160, 110, 20);

        jButton1.setText("ADICIONAR QUESTÃO");
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 590, 150, 30);

        jLabel7.setText("Resposta");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 560, 60, 14);

        jTextNome_Exercicios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome_Exercicios3);
        jTextNome_Exercicios3.setBounds(70, 210, 130, 20);

        jButton2.setText("ADICIONAR OPÇÃO");
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 500, 140, 30);

        jTextNome_Exercicios4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNome_Exercicios4);
        jTextNome_Exercicios4.setBounds(110, 460, 430, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNome_ExerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_ExerciciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_ExerciciosActionPerformed

    private void jTextQuestao_Exercicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuestao_Exercicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestao_Exercicios1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextNome_Exercicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios1ActionPerformed

    private void jTextNome_Exercicios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios3ActionPerformed

    private void jTextNome_Exercicios4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarExercicios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarExercicios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextNome_Exercicios;
    private javax.swing.JTextField jTextNome_Exercicios1;
    private javax.swing.JTextField jTextNome_Exercicios3;
    private javax.swing.JTextField jTextNome_Exercicios4;
    private javax.swing.JTextField jTextQuestao_Exercicios1;
    // End of variables declaration//GEN-END:variables
}
