/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.*;

/**
 *
 * @author sala18a
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form TelaAlunos
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pAluno = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        bCadastroProf = new javax.swing.JButton();
        bCadastroAluno = new javax.swing.JButton();
        bLogar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bExerciciosAluno = new javax.swing.JButton();
        bNotasAluno = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextQuestao_Exercicios1 = new javax.swing.JTextField();
        bVoltarExercicios = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        bVoltarNota = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextCod_alunos3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextNome_alunos2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextNome_alunos1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextNome_alunos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        bVoltarCadastroAluno = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextEmail_Professor = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        JTextNome_Professor = new javax.swing.JTextField();
        jTexIdade_Professor = new javax.swing.JTextField();
        jTextCPF_Professor = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextTurno_Professor = new javax.swing.JTextField();
        jTextLogin_Professor = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPassword_Professor = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        bVoltarCadastroProf = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        bExerciciosProf = new javax.swing.JButton();
        bNotaProf = new javax.swing.JButton();
        bCriarExerciciosProf = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextQuestao_Exercicios2 = new javax.swing.JTextField();
        bVoltarExercicios1 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextNome_Exercicios = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextQuestao_Exercicios3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jTextNome_Exercicios1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextNome_Exercicios3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jTextNome_Exercicios4 = new javax.swing.JTextField();
        bVoltarCriarExercicios = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        bVoltarNotaProf = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        bVoltarCriarExercicios1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pAluno.setLayout(new java.awt.CardLayout());

        jPanel7.setLayout(null);

        bCadastroProf.setBackground(new java.awt.Color(153, 0, 153));
        bCadastroProf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bCadastroProf.setForeground(new java.awt.Color(255, 255, 153));
        bCadastroProf.setText("Cadastro Professor");
        bCadastroProf.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        bCadastroProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastroProfActionPerformed(evt);
            }
        });
        jPanel7.add(bCadastroProf);
        bCadastroProf.setBounds(40, 430, 150, 50);

        bCadastroAluno.setBackground(new java.awt.Color(153, 0, 153));
        bCadastroAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bCadastroAluno.setForeground(new java.awt.Color(255, 255, 153));
        bCadastroAluno.setText("Cadastro Aluno");
        bCadastroAluno.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        bCadastroAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastroAlunoActionPerformed(evt);
            }
        });
        jPanel7.add(bCadastroAluno);
        bCadastroAluno.setBounds(370, 430, 150, 50);

        bLogar.setBackground(new java.awt.Color(153, 0, 153));
        bLogar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bLogar.setForeground(new java.awt.Color(255, 255, 153));
        bLogar.setText("Entrar");
        bLogar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        bLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogarActionPerformed(evt);
            }
        });
        jPanel7.add(bLogar);
        bLogar.setBounds(230, 430, 100, 50);

        jPasswordField1.setText("SENHAlegal");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jPanel7.add(jPasswordField1);
        jPasswordField1.setBounds(200, 300, 180, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Senha");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(200, 280, 50, 20);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setText("UAU4324254");
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel7.add(jTextField3);
        jTextField3.setBounds(200, 230, 180, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Usuario");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(200, 210, 60, 20);

        jPanel8.setBackground(new java.awt.Color(153, 0, 153));
        jPanel8.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 153));
        jLabel9.setText("Login");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(240, 30, 170, 60);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 610, 120);

        pAluno.add(jPanel7, "cLogin");

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Aluno");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(230, -30, 330, 230);

        bExerciciosAluno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bExerciciosAluno.setText("EXERCÍCIOS");
        bExerciciosAluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bExerciciosAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bExerciciosAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExerciciosAlunoActionPerformed(evt);
            }
        });

        bNotasAluno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bNotasAluno.setText("NOTAS");
        bNotasAluno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bNotasAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bNotasAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNotasAlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bExerciciosAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bNotasAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bExerciciosAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bNotasAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
        );

        pAluno.add(jPanel1, "cAluno");

        jPanel4.setBackground(new java.awt.Color(153, 0, 153));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Exercicios");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(180, 50, 334, 75);

        jLabel3.setText("TÍTULO");

        jTextQuestao_Exercicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuestao_Exercicios1ActionPerformed(evt);
            }
        });

        bVoltarExercicios.setBackground(new java.awt.Color(153, 0, 153));
        bVoltarExercicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarExercicios.setForeground(new java.awt.Color(255, 255, 153));
        bVoltarExercicios.setText("Voltar");
        bVoltarExercicios.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        bVoltarExercicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarExercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarExerciciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bVoltarExercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextQuestao_Exercicios1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextQuestao_Exercicios1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(bVoltarExercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pAluno.add(jPanel3, "cExercicios");

        jPanel6.setBackground(new java.awt.Color(153, 0, 153));
        jPanel6.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("NOTA ALUNO");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(150, 50, 400, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Título");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nota");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        bVoltarNota.setBackground(new java.awt.Color(153, 0, 153));
        bVoltarNota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarNota.setForeground(new java.awt.Color(255, 255, 153));
        bVoltarNota.setText("Voltar");
        bVoltarNota.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        bVoltarNota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(bVoltarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(267, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addComponent(bVoltarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pAluno.add(jPanel5, "cNotaAluno");

        jPanel9.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(153, 0, 153));
        jPanel10.setToolTipText("Teste");
        jPanel10.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 153));
        jLabel10.setText("Cadastro Aluno");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.setFocusable(false);
        jPanel10.add(jLabel10);
        jLabel10.setBounds(210, 0, 340, 100);

        jPanel9.add(jPanel10);
        jPanel10.setBounds(0, 0, 610, 100);
        jPanel9.add(jPasswordField2);
        jPasswordField2.setBounds(80, 290, 80, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Noturno", "Integral" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel9.add(jComboBox2);
        jComboBox2.setBounds(80, 200, 90, 20);

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton3);
        jButton3.setBounds(250, 380, 90, 23);

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2);
        jButton2.setBounds(50, 380, 63, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        jPanel9.add(jComboBox1);
        jComboBox1.setBounds(90, 140, 40, 20);

        jLabel11.setText("Senha");
        jPanel9.add(jLabel11);
        jLabel11.setBounds(40, 290, 60, 14);

        jTextCod_alunos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCod_alunos3ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextCod_alunos3);
        jTextCod_alunos3.setBounds(80, 260, 75, 20);

        jLabel12.setText("Login");
        jPanel9.add(jLabel12);
        jLabel12.setBounds(40, 260, 63, 14);

        jTextNome_alunos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_alunos2ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextNome_alunos2);
        jTextNome_alunos2.setBounds(80, 230, 170, 20);

        jLabel13.setText("Email");
        jPanel9.add(jLabel13);
        jLabel13.setBounds(40, 230, 60, 14);

        jLabel14.setText("Turno");
        jPanel9.add(jLabel14);
        jLabel14.setBounds(40, 200, 63, 14);

        jTextNome_alunos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_alunos1ActionPerformed(evt);
            }
        });
        jPanel9.add(jTextNome_alunos1);
        jTextNome_alunos1.setBounds(90, 170, 50, 20);

        jLabel15.setText("Matricula");
        jPanel9.add(jLabel15);
        jLabel15.setBounds(40, 170, 60, 14);

        jLabel16.setText("Série");
        jPanel9.add(jLabel16);
        jLabel16.setBounds(40, 140, 63, 14);

        jTextNome_alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_alunosActionPerformed(evt);
            }
        });
        jPanel9.add(jTextNome_alunos);
        jTextNome_alunos.setBounds(80, 110, 100, 20);

        jLabel17.setText("Nome");
        jPanel9.add(jLabel17);
        jLabel17.setBounds(40, 110, 60, 14);

        bVoltarCadastroAluno.setBackground(new java.awt.Color(153, 0, 153));
        bVoltarCadastroAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarCadastroAluno.setForeground(new java.awt.Color(255, 255, 153));
        bVoltarCadastroAluno.setText("Voltar");
        bVoltarCadastroAluno.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        bVoltarCadastroAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarCadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarCadastroAlunoActionPerformed(evt);
            }
        });
        jPanel9.add(bVoltarCadastroAluno);
        bVoltarCadastroAluno.setBounds(490, 440, 80, 40);

        pAluno.add(jPanel9, "cCadastroAluno");

        jPanel11.setLayout(null);

        jLabel18.setText("Nome");
        jLabel18.setAlignmentY(1.0F);
        jPanel11.add(jLabel18);
        jLabel18.setBounds(20, 150, 60, 30);

        jLabel19.setText("Idade");
        jPanel11.add(jLabel19);
        jLabel19.setBounds(20, 190, 50, 14);

        jLabel20.setText("CPF");
        jPanel11.add(jLabel20);
        jLabel20.setBounds(20, 230, 50, 14);

        jLabel21.setText("RG");
        jPanel11.add(jLabel21);
        jLabel21.setBounds(20, 270, 30, 14);

        jLabel22.setText("Turno");
        jPanel11.add(jLabel22);
        jLabel22.setBounds(20, 310, 50, 14);

        jLabel23.setText("Senha");
        jPanel11.add(jLabel23);
        jLabel23.setBounds(20, 430, 60, 14);

        jLabel24.setText("Login");
        jPanel11.add(jLabel24);
        jLabel24.setBounds(20, 390, 50, 14);

        jTextEmail_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmail_ProfessorActionPerformed(evt);
            }
        });
        jPanel11.add(jTextEmail_Professor);
        jTextEmail_Professor.setBounds(80, 350, 250, 20);

        jPanel12.setBackground(new java.awt.Color(153, 0, 153));
        jPanel12.setToolTipText("Teste");
        jPanel12.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 153));
        jLabel25.setText("Cadastro Professor");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel25.setFocusable(false);
        jPanel12.add(jLabel25);
        jLabel25.setBounds(180, 30, 320, 90);

        jPanel11.add(jPanel12);
        jPanel12.setBounds(0, 0, 600, 150);

        JTextNome_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextNome_ProfessorActionPerformed(evt);
            }
        });
        jPanel11.add(JTextNome_Professor);
        JTextNome_Professor.setBounds(80, 160, 200, 20);

        jTexIdade_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexIdade_ProfessorActionPerformed(evt);
            }
        });
        jPanel11.add(jTexIdade_Professor);
        jTexIdade_Professor.setBounds(80, 190, 40, 20);

        jTextCPF_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCPF_ProfessorActionPerformed(evt);
            }
        });
        jPanel11.add(jTextCPF_Professor);
        jTextCPF_Professor.setBounds(80, 230, 120, 20);

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        jPanel11.add(jTextField18);
        jTextField18.setBounds(80, 270, 90, 20);

        jTextTurno_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTurno_ProfessorActionPerformed(evt);
            }
        });
        jPanel11.add(jTextTurno_Professor);
        jTextTurno_Professor.setBounds(80, 310, 30, 20);

        jTextLogin_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLogin_ProfessorActionPerformed(evt);
            }
        });
        jPanel11.add(jTextLogin_Professor);
        jTextLogin_Professor.setBounds(80, 390, 130, 20);

        jLabel26.setText("E-MAIL");
        jPanel11.add(jLabel26);
        jLabel26.setBounds(20, 350, 60, 14);
        jPanel11.add(jSeparator2);
        jSeparator2.setBounds(0, 380, 790, 20);
        jPanel11.add(jPassword_Professor);
        jPassword_Professor.setBounds(80, 430, 130, 20);

        jButton1.setText("Cancelar");
        jPanel11.add(jButton1);
        jButton1.setBounds(230, 460, 90, 23);

        jButton4.setText("Salvar");
        jPanel11.add(jButton4);
        jButton4.setBounds(30, 460, 63, 23);

        bVoltarCadastroProf.setBackground(new java.awt.Color(153, 0, 153));
        bVoltarCadastroProf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarCadastroProf.setForeground(new java.awt.Color(255, 255, 153));
        bVoltarCadastroProf.setText("Voltar");
        bVoltarCadastroProf.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        bVoltarCadastroProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarCadastroProfActionPerformed(evt);
            }
        });
        jPanel11.add(bVoltarCadastroProf);
        bVoltarCadastroProf.setBounds(490, 440, 80, 40);

        pAluno.add(jPanel11, "cCadastroProf");

        jPanel14.setBackground(new java.awt.Color(153, 0, 153));
        jPanel14.setForeground(new java.awt.Color(153, 0, 153));

        jLabel27.setBackground(new java.awt.Color(255, 255, 153));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 102));
        jLabel27.setText("Professor");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel27)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(65, 65, 65))
        );

        bExerciciosProf.setText("EXERCÍCIOS");
        bExerciciosProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bExerciciosProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bExerciciosProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExerciciosProfActionPerformed(evt);
            }
        });

        bNotaProf.setText("NOTAS");
        bNotaProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bNotaProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bNotaProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNotaProfActionPerformed(evt);
            }
        });

        bCriarExerciciosProf.setText("CRIAR EXERCÍCIOS");
        bCriarExerciciosProf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bCriarExerciciosProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCriarExerciciosProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCriarExerciciosProfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(bExerciciosProf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bCriarExerciciosProf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bNotaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNotaProf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bExerciciosProf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCriarExerciciosProf, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
        );

        pAluno.add(jPanel13, "cProfessor");

        jPanel15.setPreferredSize(new java.awt.Dimension(612, 500));

        jPanel16.setBackground(new java.awt.Color(153, 0, 153));
        jPanel16.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 0));
        jLabel28.setText("Exercicios");
        jPanel16.add(jLabel28);
        jLabel28.setBounds(180, 40, 334, 75);

        jLabel29.setText("TÍTULO");

        jTextQuestao_Exercicios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuestao_Exercicios2ActionPerformed(evt);
            }
        });

        bVoltarExercicios1.setBackground(new java.awt.Color(153, 0, 153));
        bVoltarExercicios1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarExercicios1.setForeground(new java.awt.Color(255, 255, 153));
        bVoltarExercicios1.setText("Voltar");
        bVoltarExercicios1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        bVoltarExercicios1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarExercicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarExercicios1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextQuestao_Exercicios2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel29))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(bVoltarExercicios1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextQuestao_Exercicios2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(bVoltarExercicios1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        pAluno.add(jPanel15, "cExercicios");

        jPanel17.setLayout(null);

        jPanel18.setBackground(new java.awt.Color(153, 0, 153));
        jPanel18.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 0));
        jLabel30.setText("Criar Exercícios");
        jPanel18.add(jLabel30);
        jLabel30.setBounds(130, 30, 410, 75);

        jPanel17.add(jPanel18);
        jPanel18.setBounds(0, 0, 600, 140);

        jLabel31.setText("Professor");
        jPanel17.add(jLabel31);
        jLabel31.setBounds(20, 160, 70, 14);

        jTextNome_Exercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_ExerciciosActionPerformed(evt);
            }
        });
        jPanel17.add(jTextNome_Exercicios);
        jTextNome_Exercicios.setBounds(100, 430, 30, 20);

        jLabel32.setText("Questão ");
        jPanel17.add(jLabel32);
        jLabel32.setBounds(20, 220, 60, 20);

        jTextQuestao_Exercicios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuestao_Exercicios3ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextQuestao_Exercicios3);
        jTextQuestao_Exercicios3.setBounds(20, 240, 450, 100);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel17.add(jRadioButton1);
        jRadioButton1.setBounds(30, 350, 21, 21);

        jLabel33.setText("Título");
        jPanel17.add(jLabel33);
        jLabel33.setBounds(20, 190, 70, 14);

        jTextNome_Exercicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios1ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextNome_Exercicios1);
        jTextNome_Exercicios1.setBounds(80, 160, 110, 20);

        jButton5.setText("ADICIONAR QUESTÃO");
        jPanel17.add(jButton5);
        jButton5.setBounds(20, 460, 160, 30);

        jLabel34.setText("Resposta");
        jPanel17.add(jLabel34);
        jLabel34.setBounds(30, 430, 60, 14);

        jTextNome_Exercicios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios3ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextNome_Exercicios3);
        jTextNome_Exercicios3.setBounds(80, 190, 130, 20);

        jButton7.setText("ADICIONAR OPÇÃO");
        jPanel17.add(jButton7);
        jButton7.setBounds(30, 390, 140, 30);

        jTextNome_Exercicios4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios4ActionPerformed(evt);
            }
        });
        jPanel17.add(jTextNome_Exercicios4);
        jTextNome_Exercicios4.setBounds(70, 350, 430, 30);

        bVoltarCriarExercicios.setBackground(new java.awt.Color(153, 0, 153));
        bVoltarCriarExercicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarCriarExercicios.setForeground(new java.awt.Color(255, 255, 153));
        bVoltarCriarExercicios.setText("Voltar");
        bVoltarCriarExercicios.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        bVoltarCriarExercicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarCriarExercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarCriarExerciciosActionPerformed(evt);
            }
        });
        jPanel17.add(bVoltarCriarExercicios);
        bVoltarCriarExercicios.setBounds(390, 440, 100, 50);

        pAluno.add(jPanel17, "cCriarExercicios");

        jPanel19.setLayout(null);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel19.add(jTextField4);
        jTextField4.setBounds(90, 150, 244, 31);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Aluno");
        jPanel19.add(jLabel35);
        jLabel35.setBounds(20, 220, 50, 20);

        bVoltarNotaProf.setBackground(new java.awt.Color(153, 0, 153));
        bVoltarNotaProf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarNotaProf.setForeground(new java.awt.Color(255, 255, 153));
        bVoltarNotaProf.setText("Voltar");
        bVoltarNotaProf.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        bVoltarNotaProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarNotaProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarNotaProfActionPerformed(evt);
            }
        });
        jPanel19.add(bVoltarNotaProf);
        bVoltarNotaProf.setBounds(30, 560, 100, 50);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel19.add(jTextField5);
        jTextField5.setBounds(90, 210, 190, 31);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Nota");
        jPanel19.add(jLabel36);
        jLabel36.setBounds(20, 280, 50, 20);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel19.add(jTextField6);
        jTextField6.setBounds(90, 270, 57, 31);

        jPanel20.setBackground(new java.awt.Color(153, 0, 153));
        jPanel20.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 153));
        jLabel37.setText("NOTA PROFESSOR");
        jPanel20.add(jLabel37);
        jLabel37.setBounds(80, 30, 500, 60);

        jPanel19.add(jPanel20);
        jPanel20.setBounds(6, 0, 600, 120);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Título");
        jPanel19.add(jLabel38);
        jLabel38.setBounds(20, 160, 60, 20);

        bVoltarCriarExercicios1.setBackground(new java.awt.Color(153, 0, 153));
        bVoltarCriarExercicios1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarCriarExercicios1.setForeground(new java.awt.Color(255, 255, 153));
        bVoltarCriarExercicios1.setText("Voltar");
        bVoltarCriarExercicios1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 0, 153), new java.awt.Color(153, 0, 153)));
        bVoltarCriarExercicios1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarCriarExercicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarCriarExercicios1ActionPerformed(evt);
            }
        });
        jPanel19.add(bVoltarCriarExercicios1);
        bVoltarCriarExercicios1.setBounds(410, 430, 100, 50);

        pAluno.add(jPanel19, "cNotaProf");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExerciciosAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExerciciosAlunoActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cExercicios");
    }//GEN-LAST:event_bExerciciosAlunoActionPerformed

    private void bNotasAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNotasAlunoActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cNotaAluno");
    }//GEN-LAST:event_bNotasAlunoActionPerformed

    private void jTextQuestao_Exercicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuestao_Exercicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestao_Exercicios1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void bVoltarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarNotaActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cAluno");
    }//GEN-LAST:event_bVoltarNotaActionPerformed

    private void bVoltarExerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarExerciciosActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cAluno");
    }//GEN-LAST:event_bVoltarExerciciosActionPerformed

    private void bCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastroProfActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cCadastroProf");
    }//GEN-LAST:event_bCadastroProfActionPerformed

    private void bCadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastroAlunoActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cCadastroAluno");
    }//GEN-LAST:event_bCadastroAlunoActionPerformed

    private void bLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogarActionPerformed
        // Checar com um if se a senha encoded eh == a senha enconded no banco de dados
        //caso n seja igual, aparecer erro (popup ou texto vermelho embaixo) mas caso seja
        //passar de painel
        //botar isso dentro de um if
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cAluno");
        
        
        //Entrar no do professor caso login seja para professor
        //CardLayout card = (CardLayout)pAluno.getLayout();
        //card.show(pAluno, "cProfessor");

    }//GEN-LAST:event_bLogarActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextCod_alunos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCod_alunos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCod_alunos3ActionPerformed

    private void jTextNome_alunos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_alunos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_alunos2ActionPerformed

    private void jTextNome_alunos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_alunos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_alunos1ActionPerformed

    private void jTextNome_alunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_alunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_alunosActionPerformed

    private void bVoltarCadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarCadastroAlunoActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cLogin");
    }//GEN-LAST:event_bVoltarCadastroAlunoActionPerformed

    private void jTextEmail_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmail_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmail_ProfessorActionPerformed

    private void JTextNome_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNome_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextNome_ProfessorActionPerformed

    private void jTexIdade_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexIdade_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexIdade_ProfessorActionPerformed

    private void jTextCPF_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCPF_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCPF_ProfessorActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextTurno_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTurno_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTurno_ProfessorActionPerformed

    private void jTextLogin_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLogin_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLogin_ProfessorActionPerformed

    private void bVoltarCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarCadastroProfActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cLogin");
    }//GEN-LAST:event_bVoltarCadastroProfActionPerformed

    private void bExerciciosProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExerciciosProfActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cExercicios");
    }//GEN-LAST:event_bExerciciosProfActionPerformed

    private void bNotaProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNotaProfActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cNotaProf");
    }//GEN-LAST:event_bNotaProfActionPerformed

    private void bCriarExerciciosProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCriarExerciciosProfActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cCriarExercicios");
    }//GEN-LAST:event_bCriarExerciciosProfActionPerformed

    private void jTextQuestao_Exercicios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuestao_Exercicios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestao_Exercicios2ActionPerformed

    private void bVoltarExercicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarExercicios1ActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cProfessor");
    }//GEN-LAST:event_bVoltarExercicios1ActionPerformed

    private void jTextNome_ExerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_ExerciciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_ExerciciosActionPerformed

    private void jTextQuestao_Exercicios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuestao_Exercicios3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestao_Exercicios3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextNome_Exercicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios1ActionPerformed

    private void jTextNome_Exercicios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios3ActionPerformed

    private void jTextNome_Exercicios4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios4ActionPerformed

    private void bVoltarCriarExerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarCriarExerciciosActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cProfessor");
    }//GEN-LAST:event_bVoltarCriarExerciciosActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void bVoltarNotaProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarNotaProfActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cProfessor");
    }//GEN-LAST:event_bVoltarNotaProfActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void bVoltarCriarExercicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarCriarExercicios1ActionPerformed
        CardLayout card = (CardLayout)pAluno.getLayout();
        card.show(pAluno, "cProfessor");
    }//GEN-LAST:event_bVoltarCriarExercicios1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextNome_Professor;
    private javax.swing.JButton bCadastroAluno;
    private javax.swing.JButton bCadastroProf;
    private javax.swing.JButton bCriarExerciciosProf;
    private javax.swing.JButton bExerciciosAluno;
    private javax.swing.JButton bExerciciosProf;
    private javax.swing.JButton bLogar;
    private javax.swing.JButton bNotaProf;
    private javax.swing.JButton bNotasAluno;
    private javax.swing.JButton bVoltarCadastroAluno;
    private javax.swing.JButton bVoltarCadastroProf;
    private javax.swing.JButton bVoltarCriarExercicios;
    private javax.swing.JButton bVoltarCriarExercicios1;
    private javax.swing.JButton bVoltarExercicios;
    private javax.swing.JButton bVoltarExercicios1;
    private javax.swing.JButton bVoltarNota;
    private javax.swing.JButton bVoltarNotaProf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPassword_Professor;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTexIdade_Professor;
    private javax.swing.JTextField jTextCPF_Professor;
    private javax.swing.JTextField jTextCod_alunos3;
    private javax.swing.JTextField jTextEmail_Professor;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextLogin_Professor;
    private javax.swing.JTextField jTextNome_Exercicios;
    private javax.swing.JTextField jTextNome_Exercicios1;
    private javax.swing.JTextField jTextNome_Exercicios3;
    private javax.swing.JTextField jTextNome_Exercicios4;
    private javax.swing.JTextField jTextNome_alunos;
    private javax.swing.JTextField jTextNome_alunos1;
    private javax.swing.JTextField jTextNome_alunos2;
    private javax.swing.JTextField jTextQuestao_Exercicios1;
    private javax.swing.JTextField jTextQuestao_Exercicios2;
    private javax.swing.JTextField jTextQuestao_Exercicios3;
    private javax.swing.JTextField jTextTurno_Professor;
    private javax.swing.JPanel pAluno;
    // End of variables declaration//GEN-END:variables
}
