/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import data.AlunosDAO;
import data.ProfessoresDAO;
import java.awt.*;
import java.util.Base64;
import javax.swing.JOptionPane;
/**
 *
 * @author sala18a
 */
public class Principal extends javax.swing.JFrame {
    
        //declara as variaveis
    private AlunosDAO alunos;
    private ProfessoresDAO professores;
    
    /**
     * Creates new form TelaAlunos
     */
    public Principal() {
        initComponents();
        //inicializa essas variaveis como os objetos q elas sao
        alunos = new AlunosDAO();
        professores = new ProfessoresDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenu = new javax.swing.JPanel();
        pLogin = new javax.swing.JPanel();
        bCadastroProf = new javax.swing.JButton();
        bCadastroAluno = new javax.swing.JButton();
        bLogar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pAluno = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        bExerciciosAluno = new javax.swing.JButton();
        bNotasAluno = new javax.swing.JButton();
        bVoltarExerciciosAluno2 = new javax.swing.JButton();
        pExerciciosAluno = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextQuestao_Exercicios1 = new javax.swing.JTextField();
        bVoltarExerciciosAluno1 = new javax.swing.JButton();
        pNotaAluno = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        bVoltarNota = new javax.swing.JButton();
        pCadastroAluno = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextCod_alunos3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextNome_alunos2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextNome_alunos1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextNome_alunos = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        pCadastroProfessor = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        JTextNome_Professor = new javax.swing.JTextField();
        jTexIdade_Professor = new javax.swing.JTextField();
        jTextCPF_Professor = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextTurno_Professor = new javax.swing.JTextField();
        jTextLogin_Professor = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPassword_Professor = new javax.swing.JPasswordField();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jTextEmail_Professor1 = new javax.swing.JTextField();
        jTextUF_Professor = new javax.swing.JTextField();
        jTextTelefone_Professor = new javax.swing.JTextField();
        jTextEndereco_Professor = new javax.swing.JTextField();
        jTextDisciplina_Professor = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        pProfessor = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        bExerciciosProf = new javax.swing.JButton();
        bNotaProf = new javax.swing.JButton();
        bExerciciosProf1 = new javax.swing.JButton();
        pExercicioProfessor = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTextQuestao_Exercicios2 = new javax.swing.JTextField();
        bVoltarExerciciosProf = new javax.swing.JButton();
        pCriarExercícios = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextNome_Exercicios = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextQuestao_Exercicios3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        jTextNome_Exercicios1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextNome_Exercicios3 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jTextNome_Exercicios4 = new javax.swing.JTextField();
        bVoltarCriarExercicios = new javax.swing.JButton();
        pNotaProfessor = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        bVoltarCriarExercicios3 = new javax.swing.JButton();
        pFazerExercicios = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextNome_Exercicios2 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextQuestao_Exercicios4 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextNome_Exercicios5 = new javax.swing.JTextField();
        bVoltarCriarExercicios2 = new javax.swing.JButton();
        bVoltarCriarExercicios4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pMenu.setLayout(new java.awt.CardLayout());

        pLogin.setLayout(null);

        bCadastroProf.setBackground(new java.awt.Color(0, 102, 0));
        bCadastroProf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bCadastroProf.setForeground(new java.awt.Color(255, 255, 255));
        bCadastroProf.setText("Cadastro Professor");
        bCadastroProf.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0)));
        bCadastroProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCadastroProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastroProfActionPerformed(evt);
            }
        });
        pLogin.add(bCadastroProf);
        bCadastroProf.setBounds(40, 430, 150, 50);

        bCadastroAluno.setBackground(new java.awt.Color(0, 102, 0));
        bCadastroAluno.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bCadastroAluno.setForeground(new java.awt.Color(255, 255, 255));
        bCadastroAluno.setText("Cadastro Aluno");
        bCadastroAluno.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0)));
        bCadastroAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bCadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCadastroAlunoActionPerformed(evt);
            }
        });
        pLogin.add(bCadastroAluno);
        bCadastroAluno.setBounds(420, 430, 150, 50);

        bLogar.setBackground(new java.awt.Color(0, 102, 0));
        bLogar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bLogar.setForeground(new java.awt.Color(255, 255, 255));
        bLogar.setText("Entrar");
        bLogar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0)));
        bLogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogarActionPerformed(evt);
            }
        });
        pLogin.add(bLogar);
        bLogar.setBounds(260, 430, 100, 50);

        jPasswordField1.setText("SENHAlegal");
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        pLogin.add(jPasswordField1);
        jPasswordField1.setBounds(200, 300, 180, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Senha");
        pLogin.add(jLabel7);
        jLabel7.setBounds(200, 280, 50, 20);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setText("UAU4324254");
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        pLogin.add(jTextField3);
        jTextField3.setBounds(200, 230, 180, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Usuário");
        pLogin.add(jLabel8);
        jLabel8.setBounds(200, 210, 70, 20);

        jPanel8.setBackground(new java.awt.Color(0, 153, 0));
        jPanel8.setLayout(null);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("LOGIN");
        jPanel8.add(jLabel9);
        jLabel9.setBounds(210, 30, 170, 60);

        pLogin.add(jPanel8);
        jPanel8.setBounds(0, 0, 610, 120);

        pMenu.add(pLogin, "cLogin");

        pAluno.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));
        jPanel2.setMaximumSize(new java.awt.Dimension(610, 610));
        jPanel2.setMinimumSize(new java.awt.Dimension(120, 120));
        jPanel2.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALUNO");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(220, -50, 330, 230);

        pAluno.add(jPanel2);
        jPanel2.setBounds(0, 0, 612, 120);

        bExerciciosAluno.setBackground(new java.awt.Color(0, 102, 0));
        bExerciciosAluno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bExerciciosAluno.setForeground(new java.awt.Color(255, 255, 255));
        bExerciciosAluno.setText("EXERCÍCIOS");
        bExerciciosAluno.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bExerciciosAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bExerciciosAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExerciciosAlunoActionPerformed(evt);
            }
        });
        pAluno.add(bExerciciosAluno);
        bExerciciosAluno.setBounds(63, 298, 190, 110);

        bNotasAluno.setBackground(new java.awt.Color(0, 102, 0));
        bNotasAluno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bNotasAluno.setForeground(new java.awt.Color(255, 255, 255));
        bNotasAluno.setText("NOTAS");
        bNotasAluno.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 0), new java.awt.Color(0, 102, 0)));
        bNotasAluno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bNotasAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNotasAlunoActionPerformed(evt);
            }
        });
        pAluno.add(bNotasAluno);
        bNotasAluno.setBounds(350, 298, 190, 110);

        bVoltarExerciciosAluno2.setBackground(new java.awt.Color(0, 102, 51));
        bVoltarExerciciosAluno2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarExerciciosAluno2.setForeground(new java.awt.Color(255, 255, 255));
        bVoltarExerciciosAluno2.setText("Voltar");
        bVoltarExerciciosAluno2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bVoltarExerciciosAluno2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarExerciciosAluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarExerciciosAluno2ActionPerformed(evt);
            }
        });
        pAluno.add(bVoltarExerciciosAluno2);
        bVoltarExerciciosAluno2.setBounds(22, 528, 100, 50);

        pMenu.add(pAluno, "cAluno");

        pExerciciosAluno.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 153, 0));
        jPanel4.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EXERCÍCIOS");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(140, 20, 334, 75);

        pExerciciosAluno.add(jPanel4);
        jPanel4.setBounds(0, 0, 640, 120);

        jTextQuestao_Exercicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuestao_Exercicios1ActionPerformed(evt);
            }
        });
        pExerciciosAluno.add(jTextQuestao_Exercicios1);
        jTextQuestao_Exercicios1.setBounds(22, 169, 485, 181);

        bVoltarExerciciosAluno1.setBackground(new java.awt.Color(0, 102, 51));
        bVoltarExerciciosAluno1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarExerciciosAluno1.setForeground(new java.awt.Color(255, 255, 255));
        bVoltarExerciciosAluno1.setText("Voltar");
        bVoltarExerciciosAluno1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bVoltarExerciciosAluno1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarExerciciosAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarExerciciosAluno1ActionPerformed(evt);
            }
        });
        pExerciciosAluno.add(bVoltarExerciciosAluno1);
        bVoltarExerciciosAluno1.setBounds(22, 528, 100, 50);

        pMenu.add(pExerciciosAluno, "cExerciciosAluno");

        jPanel6.setBackground(new java.awt.Color(0, 153, 0));
        jPanel6.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOTA ALUNO");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(150, 30, 400, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Título");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Nota");

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        bVoltarNota.setBackground(new java.awt.Color(0, 102, 51));
        bVoltarNota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarNota.setForeground(new java.awt.Color(255, 255, 255));
        bVoltarNota.setText("Voltar");
        bVoltarNota.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bVoltarNota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarNotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pNotaAlunoLayout = new javax.swing.GroupLayout(pNotaAluno);
        pNotaAluno.setLayout(pNotaAlunoLayout);
        pNotaAlunoLayout.setHorizontalGroup(
            pNotaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pNotaAlunoLayout.createSequentialGroup()
                .addGroup(pNotaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNotaAlunoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pNotaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pNotaAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pNotaAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pNotaAlunoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(bVoltarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pNotaAlunoLayout.setVerticalGroup(
            pNotaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pNotaAlunoLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(pNotaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNotaAlunoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pNotaAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pNotaAlunoLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addComponent(bVoltarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pMenu.add(pNotaAluno, "cNotaAluno");

        pCadastroAluno.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(0, 153, 0));
        jPanel10.setToolTipText("Teste");
        jPanel10.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CADASTRO ALUNO");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel10.setFocusable(false);
        jPanel10.add(jLabel10);
        jLabel10.setBounds(80, -20, 510, 150);

        pCadastroAluno.add(jPanel10);
        jPanel10.setBounds(0, 0, 610, 100);
        pCadastroAluno.add(jPasswordField2);
        jPasswordField2.setBounds(80, 290, 80, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matutino", "Vespertino", "Noturno", "Integral" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        pCadastroAluno.add(jComboBox2);
        jComboBox2.setBounds(80, 200, 90, 20);

        jButton2.setBackground(new java.awt.Color(0, 102, 51));
        jButton2.setText("Voltar");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pCadastroAluno.add(jButton2);
        jButton2.setBounds(280, 430, 90, 50);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        pCadastroAluno.add(jComboBox1);
        jComboBox1.setBounds(90, 140, 40, 20);

        jLabel11.setText("Senha");
        pCadastroAluno.add(jLabel11);
        jLabel11.setBounds(40, 290, 60, 14);

        jTextCod_alunos3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCod_alunos3ActionPerformed(evt);
            }
        });
        pCadastroAluno.add(jTextCod_alunos3);
        jTextCod_alunos3.setBounds(80, 260, 75, 20);

        jLabel12.setText("Login");
        pCadastroAluno.add(jLabel12);
        jLabel12.setBounds(40, 260, 63, 14);

        jTextNome_alunos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_alunos2ActionPerformed(evt);
            }
        });
        pCadastroAluno.add(jTextNome_alunos2);
        jTextNome_alunos2.setBounds(80, 230, 170, 20);

        jLabel13.setText("Email");
        pCadastroAluno.add(jLabel13);
        jLabel13.setBounds(40, 230, 60, 14);

        jLabel14.setText("Turno");
        pCadastroAluno.add(jLabel14);
        jLabel14.setBounds(40, 200, 63, 14);

        jTextNome_alunos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_alunos1ActionPerformed(evt);
            }
        });
        pCadastroAluno.add(jTextNome_alunos1);
        jTextNome_alunos1.setBounds(90, 170, 50, 20);

        jLabel15.setText("Matricula");
        pCadastroAluno.add(jLabel15);
        jLabel15.setBounds(30, 170, 60, 14);

        jLabel16.setText("Série");
        pCadastroAluno.add(jLabel16);
        jLabel16.setBounds(40, 140, 63, 14);

        jTextNome_alunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_alunosActionPerformed(evt);
            }
        });
        pCadastroAluno.add(jTextNome_alunos);
        jTextNome_alunos.setBounds(80, 110, 100, 20);

        jLabel17.setText("Nome");
        pCadastroAluno.add(jLabel17);
        jLabel17.setBounds(40, 110, 60, 14);

        jButton6.setBackground(new java.awt.Color(0, 102, 51));
        jButton6.setText("Salvar");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pCadastroAluno.add(jButton6);
        jButton6.setBounds(180, 430, 90, 50);

        pMenu.add(pCadastroAluno, "cCadastroAluno");

        pCadastroProfessor.setLayout(null);

        jLabel18.setText("Nome");
        jLabel18.setAlignmentY(1.0F);
        pCadastroProfessor.add(jLabel18);
        jLabel18.setBounds(20, 150, 60, 30);

        jLabel19.setText("Idade");
        pCadastroProfessor.add(jLabel19);
        jLabel19.setBounds(20, 190, 50, 14);

        jLabel20.setText("CPF");
        pCadastroProfessor.add(jLabel20);
        jLabel20.setBounds(20, 230, 50, 14);

        jLabel21.setText("RG");
        pCadastroProfessor.add(jLabel21);
        jLabel21.setBounds(20, 270, 30, 14);

        jLabel22.setText("Turno");
        pCadastroProfessor.add(jLabel22);
        jLabel22.setBounds(20, 310, 50, 14);

        jLabel23.setText("Senha");
        pCadastroProfessor.add(jLabel23);
        jLabel23.setBounds(10, 570, 60, 14);

        jLabel24.setText("Login");
        pCadastroProfessor.add(jLabel24);
        jLabel24.setBounds(10, 540, 50, 14);

        jPanel12.setBackground(new java.awt.Color(0, 153, 0));
        jPanel12.setToolTipText("Teste");
        jPanel12.setLayout(null);

        jLabel25.setBackground(new java.awt.Color(0, 153, 0));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("CADASTRO PROFESSOR");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel25.setFocusable(false);
        jPanel12.add(jLabel25);
        jLabel25.setBounds(20, -30, 600, 190);

        pCadastroProfessor.add(jPanel12);
        jPanel12.setBounds(0, 0, 620, 120);

        JTextNome_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextNome_ProfessorActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(JTextNome_Professor);
        JTextNome_Professor.setBounds(80, 160, 200, 20);

        jTexIdade_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexIdade_ProfessorActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jTexIdade_Professor);
        jTexIdade_Professor.setBounds(80, 190, 40, 20);

        jTextCPF_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCPF_ProfessorActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jTextCPF_Professor);
        jTextCPF_Professor.setBounds(80, 230, 120, 20);

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jTextField18);
        jTextField18.setBounds(80, 270, 90, 20);

        jTextTurno_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTurno_ProfessorActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jTextTurno_Professor);
        jTextTurno_Professor.setBounds(80, 310, 30, 20);

        jTextLogin_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLogin_ProfessorActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jTextLogin_Professor);
        jTextLogin_Professor.setBounds(50, 540, 130, 20);

        jLabel26.setText("DISCIPLINA");
        pCadastroProfessor.add(jLabel26);
        jLabel26.setBounds(10, 480, 60, 20);
        pCadastroProfessor.add(jPassword_Professor);
        jPassword_Professor.setBounds(50, 570, 130, 20);

        jButton4.setBackground(new java.awt.Color(0, 102, 51));
        jButton4.setText("Salvar");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jButton4);
        jButton4.setBounds(190, 600, 66, 32);

        jButton9.setBackground(new java.awt.Color(0, 102, 51));
        jButton9.setText("Voltar");
        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jButton9);
        jButton9.setBounds(270, 600, 66, 32);
        pCadastroProfessor.add(jSeparator3);
        jSeparator3.setBounds(0, 530, 790, 10);

        jTextEmail_Professor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmail_Professor1ActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jTextEmail_Professor1);
        jTextEmail_Professor1.setBounds(80, 350, 250, 20);

        jTextUF_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUF_ProfessorActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jTextUF_Professor);
        jTextUF_Professor.setBounds(80, 390, 250, 20);

        jTextTelefone_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefone_ProfessorActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jTextTelefone_Professor);
        jTextTelefone_Professor.setBounds(80, 450, 250, 20);

        jTextEndereco_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEndereco_ProfessorActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jTextEndereco_Professor);
        jTextEndereco_Professor.setBounds(80, 420, 250, 20);

        jTextDisciplina_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDisciplina_ProfessorActionPerformed(evt);
            }
        });
        pCadastroProfessor.add(jTextDisciplina_Professor);
        jTextDisciplina_Professor.setBounds(80, 480, 250, 20);

        jLabel42.setText("E-MAIL");
        pCadastroProfessor.add(jLabel42);
        jLabel42.setBounds(20, 350, 60, 14);

        jLabel43.setText("UF");
        pCadastroProfessor.add(jLabel43);
        jLabel43.setBounds(40, 390, 60, 20);

        jLabel44.setText("ENDERECO");
        pCadastroProfessor.add(jLabel44);
        jLabel44.setBounds(20, 420, 60, 20);

        jLabel45.setText("TELEFONE");
        pCadastroProfessor.add(jLabel45);
        jLabel45.setBounds(10, 450, 60, 20);

        pMenu.add(pCadastroProfessor, "cCadastroProf");

        pProfessor.setPreferredSize(new java.awt.Dimension(600, 600));
        pProfessor.setLayout(null);

        jPanel14.setBackground(new java.awt.Color(0, 153, 0));
        jPanel14.setForeground(new java.awt.Color(153, 0, 153));

        jLabel27.setBackground(new java.awt.Color(10, 10, 10));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("PROFESSOR");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel27)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(26, 26, 26))
        );

        pProfessor.add(jPanel14);
        jPanel14.setBounds(0, 0, 620, 120);

        bExerciciosProf.setBackground(new java.awt.Color(0, 102, 51));
        bExerciciosProf.setText("CRIAR EXERCÍCIOS");
        bExerciciosProf.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bExerciciosProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bExerciciosProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExerciciosProfActionPerformed(evt);
            }
        });
        pProfessor.add(bExerciciosProf);
        bExerciciosProf.setBounds(230, 300, 150, 101);

        bNotaProf.setBackground(new java.awt.Color(0, 102, 51));
        bNotaProf.setText("NOTAS");
        bNotaProf.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bNotaProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bNotaProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNotaProfActionPerformed(evt);
            }
        });
        pProfessor.add(bNotaProf);
        bNotaProf.setBounds(410, 300, 150, 101);

        bExerciciosProf1.setBackground(new java.awt.Color(0, 102, 51));
        bExerciciosProf1.setText("EXERCÍCIOS");
        bExerciciosProf1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bExerciciosProf1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bExerciciosProf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExerciciosProf1ActionPerformed(evt);
            }
        });
        pProfessor.add(bExerciciosProf1);
        bExerciciosProf1.setBounds(60, 300, 150, 101);

        pMenu.add(pProfessor, "cProfessor");

        pExercicioProfessor.setPreferredSize(new java.awt.Dimension(612, 500));
        pExercicioProfessor.setLayout(null);

        jPanel16.setBackground(new java.awt.Color(0, 153, 0));
        jPanel16.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("EXERCÍCIOS");
        jPanel16.add(jLabel28);
        jLabel28.setBounds(150, 30, 334, 75);

        pExercicioProfessor.add(jPanel16);
        jPanel16.setBounds(0, 0, 610, 120);

        jLabel29.setText("TÍTULO");
        pExercicioProfessor.add(jLabel29);
        jLabel29.setBounds(36, 160, 36, 14);

        jTextQuestao_Exercicios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuestao_Exercicios2ActionPerformed(evt);
            }
        });
        pExercicioProfessor.add(jTextQuestao_Exercicios2);
        jTextQuestao_Exercicios2.setBounds(26, 182, 485, 181);

        bVoltarExerciciosProf.setBackground(new java.awt.Color(0, 102, 51));
        bVoltarExerciciosProf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarExerciciosProf.setForeground(new java.awt.Color(255, 255, 255));
        bVoltarExerciciosProf.setText("Voltar");
        bVoltarExerciciosProf.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bVoltarExerciciosProf.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarExerciciosProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarExerciciosProfActionPerformed(evt);
            }
        });
        pExercicioProfessor.add(bVoltarExerciciosProf);
        bVoltarExerciciosProf.setBounds(46, 515, 100, 50);

        pMenu.add(pExercicioProfessor, "cExerciciosProf");

        pCriarExercícios.setLayout(null);

        jPanel18.setBackground(new java.awt.Color(0, 153, 0));
        jPanel18.setLayout(null);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("CRIAR EXERCÍCIOS");
        jPanel18.add(jLabel30);
        jLabel30.setBounds(50, 10, 530, 100);

        pCriarExercícios.add(jPanel18);
        jPanel18.setBounds(0, 0, 610, 120);

        jLabel31.setText("Professor");
        pCriarExercícios.add(jLabel31);
        jLabel31.setBounds(20, 160, 70, 14);

        jTextNome_Exercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_ExerciciosActionPerformed(evt);
            }
        });
        pCriarExercícios.add(jTextNome_Exercicios);
        jTextNome_Exercicios.setBounds(100, 430, 30, 20);

        jLabel32.setText("Questão ");
        pCriarExercícios.add(jLabel32);
        jLabel32.setBounds(20, 220, 60, 20);

        jTextQuestao_Exercicios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuestao_Exercicios3ActionPerformed(evt);
            }
        });
        pCriarExercícios.add(jTextQuestao_Exercicios3);
        jTextQuestao_Exercicios3.setBounds(20, 240, 450, 100);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        pCriarExercícios.add(jRadioButton1);
        jRadioButton1.setBounds(30, 350, 21, 21);

        jLabel33.setText("Título");
        pCriarExercícios.add(jLabel33);
        jLabel33.setBounds(20, 190, 70, 14);

        jTextNome_Exercicios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios1ActionPerformed(evt);
            }
        });
        pCriarExercícios.add(jTextNome_Exercicios1);
        jTextNome_Exercicios1.setBounds(80, 160, 110, 20);

        jButton5.setText("ADICIONAR QUESTÃO");
        pCriarExercícios.add(jButton5);
        jButton5.setBounds(20, 460, 160, 30);

        jLabel34.setText("Resposta");
        pCriarExercícios.add(jLabel34);
        jLabel34.setBounds(30, 430, 60, 14);

        jTextNome_Exercicios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios3ActionPerformed(evt);
            }
        });
        pCriarExercícios.add(jTextNome_Exercicios3);
        jTextNome_Exercicios3.setBounds(80, 190, 130, 20);

        jButton7.setText("ADICIONAR OPÇÃO");
        pCriarExercícios.add(jButton7);
        jButton7.setBounds(30, 390, 140, 30);

        jTextNome_Exercicios4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios4ActionPerformed(evt);
            }
        });
        pCriarExercícios.add(jTextNome_Exercicios4);
        jTextNome_Exercicios4.setBounds(70, 350, 430, 30);

        bVoltarCriarExercicios.setBackground(new java.awt.Color(0, 102, 51));
        bVoltarCriarExercicios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarCriarExercicios.setForeground(new java.awt.Color(255, 255, 255));
        bVoltarCriarExercicios.setText("Voltar");
        bVoltarCriarExercicios.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bVoltarCriarExercicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarCriarExercicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarCriarExerciciosActionPerformed(evt);
            }
        });
        pCriarExercícios.add(bVoltarCriarExercicios);
        bVoltarCriarExercicios.setBounds(480, 540, 100, 50);

        pMenu.add(pCriarExercícios, "cCriarExercicios");

        pNotaProfessor.setLayout(null);

        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        pNotaProfessor.add(jTextField4);
        jTextField4.setBounds(90, 150, 244, 31);

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Aluno");
        pNotaProfessor.add(jLabel35);
        jLabel35.setBounds(20, 220, 50, 20);

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        pNotaProfessor.add(jTextField5);
        jTextField5.setBounds(90, 210, 190, 31);

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Nota");
        pNotaProfessor.add(jLabel36);
        jLabel36.setBounds(20, 280, 50, 20);

        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 102, 102), null));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        pNotaProfessor.add(jTextField6);
        jTextField6.setBounds(90, 270, 57, 31);

        jPanel20.setBackground(new java.awt.Color(0, 153, 0));
        jPanel20.setLayout(null);

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("NOTA PROFESSOR");
        jPanel20.add(jLabel37);
        jLabel37.setBounds(80, 30, 500, 60);

        pNotaProfessor.add(jPanel20);
        jPanel20.setBounds(-14, 0, 640, 120);

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Título");
        pNotaProfessor.add(jLabel38);
        jLabel38.setBounds(20, 160, 60, 20);

        bVoltarCriarExercicios3.setBackground(new java.awt.Color(0, 102, 51));
        bVoltarCriarExercicios3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarCriarExercicios3.setForeground(new java.awt.Color(255, 255, 255));
        bVoltarCriarExercicios3.setText("VOLTAR");
        bVoltarCriarExercicios3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bVoltarCriarExercicios3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarCriarExercicios3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarCriarExercicios3ActionPerformed(evt);
            }
        });
        pNotaProfessor.add(bVoltarCriarExercicios3);
        bVoltarCriarExercicios3.setBounds(10, 540, 100, 50);

        pMenu.add(pNotaProfessor, "cNotaProf");

        pFazerExercicios.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 153, 0));
        jPanel3.setLayout(null);

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText(" EXERCÍCIO");
        jPanel3.add(jLabel41);
        jLabel41.setBounds(140, 40, 289, 58);

        pFazerExercicios.add(jPanel3);
        jPanel3.setBounds(0, 0, 970, 140);

        jLabel3.setText("TÍTULO");
        pFazerExercicios.add(jLabel3);
        jLabel3.setBounds(30, 160, 40, 14);

        jTextNome_Exercicios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios2ActionPerformed(evt);
            }
        });
        pFazerExercicios.add(jTextNome_Exercicios2);
        jTextNome_Exercicios2.setBounds(60, 440, 350, 20);

        jLabel39.setText("QUESTÃO 1");
        pFazerExercicios.add(jLabel39);
        jLabel39.setBounds(20, 210, 60, 20);

        jTextQuestao_Exercicios4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextQuestao_Exercicios4ActionPerformed(evt);
            }
        });
        pFazerExercicios.add(jTextQuestao_Exercicios4);
        jTextQuestao_Exercicios4.setBounds(20, 230, 450, 160);

        jLabel40.setText("OPÇÕES");
        pFazerExercicios.add(jLabel40);
        jLabel40.setBounds(20, 420, 80, 14);

        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        pFazerExercicios.add(jRadioButton2);
        jRadioButton2.setBounds(30, 440, 21, 21);

        jTextNome_Exercicios5.setText("JAVA");
        jTextNome_Exercicios5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNome_Exercicios5ActionPerformed(evt);
            }
        });
        pFazerExercicios.add(jTextNome_Exercicios5);
        jTextNome_Exercicios5.setBounds(80, 160, 40, 20);

        bVoltarCriarExercicios2.setBackground(new java.awt.Color(0, 102, 51));
        bVoltarCriarExercicios2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarCriarExercicios2.setForeground(new java.awt.Color(255, 255, 255));
        bVoltarCriarExercicios2.setText("Voltar");
        bVoltarCriarExercicios2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bVoltarCriarExercicios2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarCriarExercicios2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarCriarExercicios2ActionPerformed(evt);
            }
        });
        pFazerExercicios.add(bVoltarCriarExercicios2);
        bVoltarCriarExercicios2.setBounds(520, 610, 70, 30);

        bVoltarCriarExercicios4.setBackground(new java.awt.Color(0, 102, 51));
        bVoltarCriarExercicios4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bVoltarCriarExercicios4.setForeground(new java.awt.Color(255, 255, 255));
        bVoltarCriarExercicios4.setText("Confirmar");
        bVoltarCriarExercicios4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 51), new java.awt.Color(0, 102, 51)));
        bVoltarCriarExercicios4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bVoltarCriarExercicios4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarCriarExercicios4ActionPerformed(evt);
            }
        });
        pFazerExercicios.add(bVoltarCriarExercicios4);
        bVoltarCriarExercicios4.setBounds(433, 610, 80, 30);

        pMenu.add(pFazerExercicios, "card12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExerciciosAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExerciciosAlunoActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cExerciciosAluno");
    }//GEN-LAST:event_bExerciciosAlunoActionPerformed

    private void bNotasAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNotasAlunoActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cNotaAluno");
    }//GEN-LAST:event_bNotasAlunoActionPerformed

    private void jTextQuestao_Exercicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuestao_Exercicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestao_Exercicios1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void bVoltarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarNotaActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cAluno");
    }//GEN-LAST:event_bVoltarNotaActionPerformed

    private void bCadastroProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastroProfActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cCadastroProf");
    }//GEN-LAST:event_bCadastroProfActionPerformed

    private void bCadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCadastroAlunoActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cCadastroAluno");
    }//GEN-LAST:event_bCadastroAlunoActionPerformed

    private void bLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogarActionPerformed
        
        alunos.aluno.setLOGIN_ALUNOS(jTextField3.getText());
        alunos.localizar();
        
        
        professores.professor.setLOGIN_PROFESSOR("usuarioDoProf (pegar da caixa de texto login)");
        //professores.localizar();
        //apos localizado,pegar a senha com o get
        //caso n seja igual, aparecer erro (popup ou texto vermelho embaixo) mas caso seja
        String encodeBytes = Base64.getEncoder().encodeToString((jPasswordField1.getText()).getBytes());
        
        //if(encodeBytes == alunos.aluno.getSENHA_ALUNOS()){
        //    CardLayout card = (CardLayout)pMenu.getLayout();
        //    card.show(pMenu, "cAluno");
        //}
        
        if(encodeBytes.equals(alunos.aluno.getSENHA_ALUNOS())){
            //dentro a parte de card layouts para a tela aluno
            CardLayout card = (CardLayout)pMenu.getLayout();
            card.show(pMenu, "cAluno");
        }
        
        else if(encodeBytes.equals(professores.professor.getSENHA_PROFESSOR())){
            //card layout do professor
            CardLayout card = (CardLayout)pAluno.getLayout();
            card.show(pAluno, "cProfessor");
        }
        
     
        
        //Entrar no do professor caso login seja para professor
        //CardLayout card = (CardLayout)pAluno.getLayout();
        //card.show(pAluno, "cProfessor");

    }//GEN-LAST:event_bLogarActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
            card.show(pMenu, "cLogin");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextCod_alunos3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCod_alunos3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCod_alunos3ActionPerformed

    private void jTextNome_alunos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_alunos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_alunos2ActionPerformed

    private void jTextNome_alunos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_alunos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_alunos1ActionPerformed

    private void jTextNome_alunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_alunosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_alunosActionPerformed

    private void JTextNome_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNome_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextNome_ProfessorActionPerformed

    private void jTexIdade_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexIdade_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexIdade_ProfessorActionPerformed

    private void jTextCPF_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCPF_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCPF_ProfessorActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextTurno_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTurno_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTurno_ProfessorActionPerformed

    private void jTextLogin_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLogin_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLogin_ProfessorActionPerformed

    private void bExerciciosProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExerciciosProfActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cExerciciosProf");
    }//GEN-LAST:event_bExerciciosProfActionPerformed

    private void bNotaProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNotaProfActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cNotaProf");
    }//GEN-LAST:event_bNotaProfActionPerformed

    private void jTextQuestao_Exercicios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuestao_Exercicios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestao_Exercicios2ActionPerformed

    private void bVoltarExerciciosProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarExerciciosProfActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cProfessor");
    }//GEN-LAST:event_bVoltarExerciciosProfActionPerformed

    private void jTextNome_ExerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_ExerciciosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_ExerciciosActionPerformed

    private void jTextQuestao_Exercicios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuestao_Exercicios3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestao_Exercicios3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jTextNome_Exercicios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios1ActionPerformed

    private void jTextNome_Exercicios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios3ActionPerformed

    private void jTextNome_Exercicios4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios4ActionPerformed

    private void bVoltarCriarExerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarCriarExerciciosActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cProfessor");
    }//GEN-LAST:event_bVoltarCriarExerciciosActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        alunos.aluno.setNOME_ALUNOS(jTextNome_alunos.getText());
        alunos.aluno.setSERIE_ALUNOS((String) jComboBox1.getSelectedItem());
        alunos.aluno.setMATRICULA_ALUNOS(jTextNome_alunos1.getText());
        alunos.aluno.setTURNO_ALUNOS((String) jComboBox2.getSelectedItem());
        alunos.aluno.setEMAIL_ALUNOS(jTextNome_alunos2.getText());
        alunos.aluno.setLOGIN_ALUNOS(jTextCod_alunos3.getText());
        alunos.aluno.setSENHA_ALUNOS(jPasswordField2.getText());
        JOptionPane.showMessageDialog(null, alunos.atualizar(AlunosDAO.INCLUSAO));
    }//GEN-LAST:event_jButton6ActionPerformed
        
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        professores.professor.setNOME_PROFESSOR(JTextNome_Professor.getText());
        professores.professor.setDISCIPLINA_PROFESSOR((String)jTextDisciplina_Professor.getText());
        professores.professor.setIDADE_PROFESSOR(jTexIdade_Professor.getText());
        professores.professor.setTELEFONE_PROFESSOR((String) jTextTelefone_Professor.getText());
        professores.professor.setENDERECO_PROFESSOR(jTextEndereco_Professor.getText());
        professores.professor.setUF_PROFESSOR(jTextUF_Professor.getText());
        professores.professor.setCIDADE_PROFESSOR(jPasswordField2.getText());
        professores.professor.setCPF_PROFESSOR(jTextCPF_Professor.getText());
        professores.professor.setRG_PROFESSOR(jTextField18.getText());
        professores.professor.setSEXO_PROFESSOR(jPasswordField2.getText());
        professores.professor.setBAIRRO_PROFESSOR(jPasswordField2.getText());
        professores.professor.setTURNO_PROFESSOR(jTextTurno_Professor.getText());
        professores.professor.setLOGIN_PROFESSOR(jPasswordField2.getText());
        professores.professor.setSENHA_PROFESSOR(jPassword_Professor.getText());
        professores.professor.setEMAIL_PROFESSOR(jTextEmail_Professor1.getText());
        JOptionPane.showMessageDialog(null, professores.atualizar(ProfessoresDAO.INCLUSAO));
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cLogin");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void bExerciciosProf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExerciciosProf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bExerciciosProf1ActionPerformed

    private void bVoltarCriarExercicios3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarCriarExercicios3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVoltarCriarExercicios3ActionPerformed

    private void bVoltarExerciciosAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarExerciciosAluno1ActionPerformed
        CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cAluno");
    }//GEN-LAST:event_bVoltarExerciciosAluno1ActionPerformed

    private void bVoltarExerciciosAluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarExerciciosAluno2ActionPerformed
         CardLayout card = (CardLayout)pMenu.getLayout();
        card.show(pMenu, "cLogin");
    }//GEN-LAST:event_bVoltarExerciciosAluno2ActionPerformed

    private void jTextNome_Exercicios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios2ActionPerformed

    private void jTextQuestao_Exercicios4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextQuestao_Exercicios4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextQuestao_Exercicios4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextNome_Exercicios5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNome_Exercicios5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNome_Exercicios5ActionPerformed

    private void bVoltarCriarExercicios2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarCriarExercicios2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVoltarCriarExercicios2ActionPerformed

    private void bVoltarCriarExercicios4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarCriarExercicios4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bVoltarCriarExercicios4ActionPerformed

    private void jTextEmail_Professor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmail_Professor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmail_Professor1ActionPerformed

    private void jTextUF_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUF_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUF_ProfessorActionPerformed

    private void jTextTelefone_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefone_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefone_ProfessorActionPerformed

    private void jTextEndereco_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEndereco_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEndereco_ProfessorActionPerformed

    private void jTextDisciplina_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDisciplina_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDisciplina_ProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextNome_Professor;
    private javax.swing.JButton bCadastroAluno;
    private javax.swing.JButton bCadastroProf;
    private javax.swing.JButton bExerciciosAluno;
    private javax.swing.JButton bExerciciosProf;
    private javax.swing.JButton bExerciciosProf1;
    private javax.swing.JButton bLogar;
    private javax.swing.JButton bNotaProf;
    private javax.swing.JButton bNotasAluno;
    private javax.swing.JButton bVoltarCriarExercicios;
    private javax.swing.JButton bVoltarCriarExercicios2;
    private javax.swing.JButton bVoltarCriarExercicios3;
    private javax.swing.JButton bVoltarCriarExercicios4;
    private javax.swing.JButton bVoltarExerciciosAluno1;
    private javax.swing.JButton bVoltarExerciciosAluno2;
    private javax.swing.JButton bVoltarExerciciosProf;
    private javax.swing.JButton bVoltarNota;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPassword_Professor;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTexIdade_Professor;
    private javax.swing.JTextField jTextCPF_Professor;
    private javax.swing.JTextField jTextCod_alunos3;
    private javax.swing.JTextField jTextDisciplina_Professor;
    private javax.swing.JTextField jTextEmail_Professor1;
    private javax.swing.JTextField jTextEndereco_Professor;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextLogin_Professor;
    private javax.swing.JTextField jTextNome_Exercicios;
    private javax.swing.JTextField jTextNome_Exercicios1;
    private javax.swing.JTextField jTextNome_Exercicios2;
    private javax.swing.JTextField jTextNome_Exercicios3;
    private javax.swing.JTextField jTextNome_Exercicios4;
    private javax.swing.JTextField jTextNome_Exercicios5;
    private javax.swing.JTextField jTextNome_alunos;
    private javax.swing.JTextField jTextNome_alunos1;
    private javax.swing.JTextField jTextNome_alunos2;
    private javax.swing.JTextField jTextQuestao_Exercicios1;
    private javax.swing.JTextField jTextQuestao_Exercicios2;
    private javax.swing.JTextField jTextQuestao_Exercicios3;
    private javax.swing.JTextField jTextQuestao_Exercicios4;
    private javax.swing.JTextField jTextTelefone_Professor;
    private javax.swing.JTextField jTextTurno_Professor;
    private javax.swing.JTextField jTextUF_Professor;
    private javax.swing.JPanel pAluno;
    private javax.swing.JPanel pCadastroAluno;
    private javax.swing.JPanel pCadastroProfessor;
    private javax.swing.JPanel pCriarExercícios;
    private javax.swing.JPanel pExercicioProfessor;
    private javax.swing.JPanel pExerciciosAluno;
    private javax.swing.JPanel pFazerExercicios;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pMenu;
    private javax.swing.JPanel pNotaAluno;
    private javax.swing.JPanel pNotaProfessor;
    private javax.swing.JPanel pProfessor;
    // End of variables declaration//GEN-END:variables
}
