/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import javax.swing.JFrame;

/**
 *
 * @author sala18a
 */
public class telaProfessor extends javax.swing.JFrame {

    /**
     * Creates new form telaProfessor
     */
    public telaProfessor() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextEmail_Professor = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        JTextNome_Professor = new javax.swing.JTextField();
        jTexIdade_Professor = new javax.swing.JTextField();
        jTextCPF_Professor = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextTurno_Professor = new javax.swing.JTextField();
        jTextLogin_Professor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPassword_Professor = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel2.setText("Nome");
        jLabel2.setAlignmentY(1.0F);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 190, 30, 30);

        jLabel3.setText("Idade");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 230, 28, 14);

        jLabel8.setText("CPF");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 270, 19, 14);

        jLabel9.setText("RG");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 310, 14, 14);

        jLabel12.setText("Turno");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 350, 28, 14);

        jLabel13.setText("Senha");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 500, 40, 14);

        jLabel14.setText("Login");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(20, 460, 25, 14);

        jTextEmail_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmail_ProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextEmail_Professor);
        jTextEmail_Professor.setBounds(80, 390, 250, 20);

        jPanel1.setBackground(new java.awt.Color(153, 0, 153));
        jPanel1.setToolTipText("Teste");
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 153));
        jLabel4.setText("Cadastro Professor");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setFocusable(false);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 20, 320, 90);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 150);

        JTextNome_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextNome_ProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(JTextNome_Professor);
        JTextNome_Professor.setBounds(80, 195, 200, 20);

        jTexIdade_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexIdade_ProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jTexIdade_Professor);
        jTexIdade_Professor.setBounds(80, 230, 30, 20);

        jTextCPF_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCPF_ProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCPF_Professor);
        jTextCPF_Professor.setBounds(80, 270, 120, 20);

        jTextField18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField18ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField18);
        jTextField18.setBounds(80, 310, 90, 20);

        jTextTurno_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTurno_ProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextTurno_Professor);
        jTextTurno_Professor.setBounds(80, 350, 30, 20);

        jTextLogin_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLogin_ProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextLogin_Professor);
        jTextLogin_Professor.setBounds(80, 460, 130, 20);

        jLabel1.setText("E-MAIL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 390, 34, 14);
        getContentPane().add(filler1);
        filler1.setBounds(40, 430, 240, 0);
        getContentPane().add(filler2);
        filler2.setBounds(30, 430, 740, 0);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(240, 430, 50, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 440, 790, 20);
        getContentPane().add(jPassword_Professor);
        jPassword_Professor.setBounds(80, 500, 130, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextEmail_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmail_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEmail_ProfessorActionPerformed

    private void JTextNome_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextNome_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextNome_ProfessorActionPerformed

    private void jTexIdade_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexIdade_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexIdade_ProfessorActionPerformed

    private void jTextCPF_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCPF_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCPF_ProfessorActionPerformed

    private void jTextField18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18ActionPerformed

    private void jTextTurno_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTurno_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTurno_ProfessorActionPerformed

    private void jTextLogin_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLogin_ProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLogin_ProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaProfessor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextNome_Professor;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword_Professor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTexIdade_Professor;
    private javax.swing.JTextField jTextCPF_Professor;
    private javax.swing.JTextField jTextEmail_Professor;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextLogin_Professor;
    private javax.swing.JTextField jTextTurno_Professor;
    // End of variables declaration//GEN-END:variables
}
